//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleBlog.DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Post
    {
        public int IdPost { get; set; }
        [Required(ErrorMessage ="Tytu³ jest wymagany!")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Treœæ jest wymagana!")]
        public string Content { get; set; }
        [Required(ErrorMessage = "Obrazek jest wymagany!")]
        [Url(ErrorMessage = "Podaj poprawny adres obrazka!")]
        public string Picture { get; set; }
        public Nullable<int> IdAuthor { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
